Repository microsoft/Git-Credential-Manager-for-Windows, pull requests merged in 2018-09, with the labels that each got.

#740 alm: fix flaky tests
  Microsoft.Alm.Authentication/Test/CredentialTests.cs
  Microsoft.Alm.Authentication/Test/TokenTests.cs
Labels: cla-signed, test-related

#753 Rebranding fixes
  Installer/Components.proj
  Installer/Installer.proj
Labels: azure-devops, build-related, cla-signed, deployment-installer

#755 devops: update requestUri for easier debugging
  VisualStudioTeamServices.Authentication/Src/Authentication.cs
Labels: azure-devops, bug

#760 build: fix argument quoting
  vsts-tt.yml
Labels: build-related

#761 version: update assembly versions
  Cli/Askpass/Properties/AssemblyInfo.cs
  Cli/Manager/Properties/AssemblyInfo.cs
  VisualStudioTeamServices.Authentication/Src/Properties/AssemblyInfo.cs
Labels: azure-devops, bug

#754 devops: update requestUri for easier debugging
  AzureDevOps.Authentication/Src/Authentication.cs
Labels: azure-devops, cla-signed

#763 cli: add GCM_HTTP_TIMEOUT and httpTimeout support
  Docs/Configuration.md
  Docs/Environment.md
  Microsoft.Alm.Authentication/Src/Global.cs
  Shared/Cli/Functions/Common.cs
  Shared/Cli/Program.cs
Labels: azure-devops, enhancement

#767 Give path priority when supplied
  Shared/Cli/OperationArguments.cs
Labels: azure-devops
