Repository microsoft/Git-Credential-Manager-for-Windows, pull requests merged in 2018-08, with the labels that each got.

#702 Improve opargs
  Cli/Manager/Program.cs
  Microsoft.Alm.Authentication/Src/Git/Configuration.cs
  Shared/Cli/AuthorityType.cs
  Shared/Cli/Functions/Bitbucket.cs
  Shared/Cli/Functions/Common.cs
  Shared/Cli/Functions/Console.cs
  Shared/Cli/Functions/Dialog.cs
  Shared/Cli/Functions/GitHub.cs
  Shared/Cli/NativeMethods.cs
  Shared/Cli/OperationArguments.cs
  Shared/Cli/Program.cs
  VisualStudioTeamServices.Authentication/Src/Authentication.cs
Labels: cla-signed, enhancement

#701 bitbucket: make very slow test fast
  Bitbucket.Authentication/Test/AuthorityTest.cs
  Bitbucket.Authentication/Test/Bitbucket.Authentication.Test.csproj
  Bitbucket.Authentication/Test/Data/AuthorityTest_VerifyAcquireTokenAcceptsValidAuthenticationResultTypes.json
Labels: bitbucket, test-related

#706 alm: complete partial cherry-pick
  Microsoft.Alm.Authentication/Src/Network.cs
Labels: bitbucket, bug, cla-signed

#707 alm: correct pass args within `Trace` methods.
  Microsoft.Alm.Authentication/Src/Git/Trace.cs
Labels: bug, cla-signed

#708 alm: correct pass args within `Trace` methods.
  Microsoft.Alm.Authentication/Src/Git/Trace.cs
Labels: bug, cla-signed

#712 bitbucket: fix data loss from token misuse
  Bitbucket.Authentication/Src/OAuth/OAuthAuthenticator.cs
  Microsoft.Alm.Authentication/Src/Network.cs
  Microsoft.Alm.Authentication/Src/Token.cs
Labels: bitbucket, bug, cla-signed

#711 bitbucket: fix data loss from token misuse
  Bitbucket.Authentication/Src/OAuth/OAuthAuthenticator.cs
  Microsoft.Alm.Authentication/Src/Network.cs
  Microsoft.Alm.Authentication/Src/Token.cs
Labels: bitbucket, bug, cla-signed

#713 bitbucket: fix authentication
  Bitbucket.Authentication/OAuth/OAuthAuthenticator.cs
  Microsoft.Alm.Authentication/Token.cs
Labels: bitbucket, bug, cla-signed

#718 build: correct pipeline builds
  vsts-ci.yml
  vsts-pr.yml
  vsts-rs.yml
  vsts-tt.yml
Labels: build-related, cla-signed

#720 bitbucket: Fixed basic auth with new username
  Bitbucket.Authentication/Src/Authentication.cs
  Bitbucket.Authentication/Src/OAuth/SimpleServer.cs
  Bitbucket.Authentication/Test/AuthenticationTest.cs
Labels: bitbucket, bug, cla-signed

#724 update versions
  Bitbucket.Authentication/Properties/AssemblyInfo.cs
  Cli-Askpass/Properties/AssemblyInfo.cs
  Cli-CredentialHelper/Properties/AssemblyInfo.cs
Labels: build-related, cla-signed

#726 build: fix CI build
  vsts-tt.yml
Labels: bug, build-related, cla-signed

#728 alm: allow tokens as basic authorization
  Microsoft.Alm.Authentication/Network.cs
Labels: bitbucket, bug

#730 build: more paramaterization
  vsts-ci.yml
  vsts-pr.yml
  vsts-rs.yml
  vsts-tt.yml
Labels: build-related, cla-signed

#731 build: fix realsign builds
  vsts-rs.yml
Labels: build-related, cla-signed

#732 bitbucket: Remove calls to Thread.Sleep
  Bitbucket.Authentication/Src/OAuth/SimpleServer.cs
Labels: bitbucket

#734 cli: use the correct string comparer.
  Shared/Cli/Functions/Common.cs
Labels: bug, cla-signed
