Repository microsoft/Git-Credential-Manager-for-Windows, pull requests merged in 2018-03, with the labels that each got.

#578 Add README instructions for installing in MSYS2
  README.md
Labels: documentation

#575 Trace-as-a-Service
  Bitbucket.Authentication/Authentication.cs
  Bitbucket.Authentication/AuthenticationPrompts.cs
  Bitbucket.Authentication/Authority.cs
  Bitbucket.Authentication/OAuth/OAuthAuthenticator.cs
  Bitbucket.Authentication/Rest/RestClient.cs
  Cli-Askpass/Program.cs
  Cli-CredentialHelper.Test/OperationArgumentsTests.cs
  Cli-CredentialHelper.Test/ProgramTests.cs
  Cli-CredentialHelper/Installer.cs
  Cli-CredentialHelper/Program.cs
  Cli-Shared/Functions/Common.cs
  Cli-Shared/Functions/Console.cs
  Cli-Shared/Functions/Dialog.cs
  Cli-Shared/Functions/GitHub.cs
  Cli-Shared/OperationArguments.cs
  Cli-Shared/Program.cs
  GitHub.Authentication/Authentication.cs
  GitHub.Authentication/AuthenticationPrompts.cs
  GitHub.Authentication/Authority.cs
  Microsoft.Alm.Authentication.Test/Git/ConfigurationTests.cs
  Microsoft.Alm.Authentication/Base.cs
  Microsoft.Alm.Authentication/BaseSecureStore.cs
  Microsoft.Alm.Authentication/BasicAuthentication.cs
  Microsoft.Alm.Authentication/Git/Configuration.cs
  Microsoft.Alm.Authentication/Git/Trace.cs
  Microsoft.Alm.Authentication/Git/Where.cs
  Microsoft.Alm.Authentication/RuntimeContext.cs
  Microsoft.Alm.Authentication/Token.cs
  Microsoft.Alm.Authentication/WwwAuthenticateHelper.cs
  Microsoft.Vsts.Authentication/AzureAuthority.cs
  Microsoft.Vsts.Authentication/BaseVstsAuthentication.cs
  Microsoft.Vsts.Authentication/TokenRegistry.cs
  Microsoft.Vsts.Authentication/VstsAadAuthentication.cs
  Microsoft.Vsts.Authentication/VstsAdalTokenCache.cs
  Microsoft.Vsts.Authentication/VstsAzureAuthority.cs
  Microsoft.Vsts.Authentication/VstsMsaAuthentication.cs
Labels: api-compatibility-break, cla-not-required, enhancement

#579 Network-as-a-Service
  Bitbucket.Authentication.Test/AuthenticationTest.cs
  Bitbucket.Authentication/Authentication.cs
  Bitbucket.Authentication/Authority.cs
  Bitbucket.Authentication/BasicAuth/BasicAuthAuthenticator.cs
  Bitbucket.Authentication/IAuthority.cs
  Bitbucket.Authentication/OAuth/OAuthAuthenticator.cs
  Bitbucket.Authentication/Rest/RestClient.cs
  Cli-Shared/Functions/Common.cs
  GitHub.Authentication/Authority.cs
  Microsoft.Alm.Authentication.Test/TargetUriTests.cs
  Microsoft.Alm.Authentication/Base.cs
  Microsoft.Alm.Authentication/BasicAuthentication.cs
  Microsoft.Alm.Authentication/Credential.cs
  Microsoft.Alm.Authentication/Microsoft.Alm.Authentication.csproj
  Microsoft.Alm.Authentication/Network.cs
  Microsoft.Alm.Authentication/RuntimeContext.cs
  Microsoft.Alm.Authentication/TargetUri.cs
  Microsoft.Alm.Authentication/Token.cs
  Microsoft.Alm.Authentication/TokenType.cs
  Microsoft.Alm.Authentication/WwwAuthenticateHelper.cs
  Microsoft.Vsts.Authentication.Test/AuthorityFake.cs
  Microsoft.Vsts.Authentication/AzureAuthority.cs
  Microsoft.Vsts.Authentication/BaseVstsAuthentication.cs
  Microsoft.Vsts.Authentication/TokenRegistry.cs
  Microsoft.Vsts.Authentication/VstsAzureAuthority.cs
Labels: api-compatibility-break, bitbucket, cla-not-required, enhancement, github, visual-studio-team-services

#580 Correct trace
  Cli-Askpass/Program.cs
  Cli-CredentialHelper/Program.cs
  Cli-Shared/Program.cs
  Microsoft.Alm.Authentication/Git/Trace.cs
Labels: cla-not-required, enhancement

#586 Use comparers to compare.
  Microsoft.Alm.Authentication.Test/Git/InstallationTests.cs
  Microsoft.Alm.Authentication/Git/Installation.cs
  Microsoft.Alm.Authentication/Git/InstallationComparer.cs
  Microsoft.Alm.Authentication/Microsoft.Alm.Authentication.csproj
Labels: cla-not-required, enhancement

#588 Rename fs
  Cli-AskPass/Program.cs
  Cli-Askpass/Program.cs
  Cli-CredentialHelper/Installer.cs
  Cli-CredentialHelper/Program.cs
  Cli-Shared/Functions/Common.cs
  Cli-Shared/Program.cs
  Microsoft.Alm.Authentication/Base.cs
  Microsoft.Alm.Authentication/Git/Configuration.cs
  Microsoft.Alm.Authentication/Git/Installation.cs
  Microsoft.Alm.Authentication/Git/Where.cs
  Microsoft.Alm.Authentication/Microsoft.Alm.Authentication.csproj
  Microsoft.Alm.Authentication/RuntimeContext.cs
  Microsoft.Alm.Authentication/Storage.cs
  Microsoft.Vsts.Authentication/BaseVstsAuthentication.cs
  Microsoft.Vsts.Authentication/VstsAdalTokenCache.cs
Labels: cla-not-required

#594 Escaping reserved characters in username when creating resposity uri (alternative implementation)
  Cli-CredentialHelper.Test/OperationArgumentsTests.cs
  Cli-Shared/OperationArguments.cs
Labels: bug, enhancement

#595 Escaping reserved characters in username when creating resposity uri
  Cli-CredentialHelper.Test/OperationArgumentsTests.cs
  Cli-Shared/OperationArguments.cs
Labels: bug

#599 cli: Update version numbers.
  Cli-Askpass/Properties/AssemblyInfo.cs
  Cli-CredentialHelper/Properties/AssemblyInfo.cs
Labels: cla-not-required

#605 Prepare v1.15.2
  Cli-Askpass/Properties/AssemblyInfo.cs
  Cli-CredentialHelper.Test/OperationArgumentsTests.cs
  Cli-CredentialHelper/Properties/AssemblyInfo.cs
  Cli-Shared/OperationArguments.cs
Labels: bug, cla-not-required
